framework:
    assets:
        packages:
            main:
                json_manifest_path: '%kernel.project_dir%/public/build/main/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'