services:
#################################################### Admin Part ########################################################
### USER / Group ###
  admin.user:
    class: App\Admin\User\UserAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\User\User, controller: App\Controller\Admin\User\UserAdminController, manager_type: orm, group: admin, label: Users }
    calls:
      - [ setUserPasswordHasher, [ '@security.user_password_hasher' ] ]
      - [ setTranslationDomain, [ 'UserAdmin' ] ]

  admin.group:
    class: App\Admin\User\GroupAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\User\Group, controller: ~, manager_type: orm, group: admin, label: Groups }
    calls:
      - [ setTranslationDomain, [ 'GroupAdmin' ] ]

  admin.client:
    class: App\Admin\User\ClientAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\User\Client, controller: ~, manager_type: orm, group: admin, label: Clients }

########################################################################################################################
######################################################## Food ##########################################################
  admin.food:
    class: App\Admin\FoodAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\Food, controller: ~, manager_type: orm, group: admin, label: Foods }
########################################################################################################################
###################################################### Activities ######################################################
  admin.activity:
    class: App\Admin\ActivityAdmin
    tags:
      - { name: sonata.admin, model_class: App\Entity\Activity, controller: ~, manager_type: orm, group: admin, label: Activities }
########################################################################################################################
