name: Deployement production - challenge-stack-1.pidok-server.fr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.PROD_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: apt update
        run:
              sudo apt update

      - name: install sshpass
        run:
              sudo apt install sshpass

      - name: deploy
        run:
              sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}
              "
              cd /user/challenge-stack-1/challenge-stack-1.pidok-server.fr &&
              git reset --hard main &&
              git pull &&
              composer install &&
              php8.1 bin/console doctrine:schema:update --force &&
              yarn install &&
              yarn build &&
              php8.1 bin/console cache:clear
              "